sylius_supplier_plugin_admin_supplier:
    resource: |
        alias: sylius_supplier_plugin.supplier
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: sylius_supplier_plugin_admin_supplier
        vars:
            all:
                subheader: sylius_supplier_plugin.ui.supplier
            index:
                icon: 'star outline'
    type: sylius.resource